import type { Metadata } from "next";
import { LEGAL, SITE } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How Portsmouth Scoop collects, uses, and protects your personal data.",
};

export default function PrivacyPage() {
  return (
    <article className="legal mx-auto max-w-3xl px-5 py-16 md:py-20">
      <h1 className="text-4xl font-extrabold tracking-tight">Privacy Policy</h1>
      <p className="mt-2 text-sm text-muted">Last updated: {LEGAL.lastUpdated}</p>

      <p>
        This policy explains how {LEGAL.controller} (&ldquo;we&rdquo;,
        &ldquo;us&rdquo;), which operates {LEGAL.brand}{" "}
        ({SITE.url.replace(/^https?:\/\//, "")}), collects and uses your personal
        data, and your rights under UK data protection law (UK GDPR and the Data
        Protection Act 2018).
      </p>

      <h2>Who we are</h2>
      <p>
        The data controller is {LEGAL.controller} (company number{" "}
        {LEGAL.companyNumber}), registered at {LEGAL.registeredAddress}. For any
        privacy questions or requests, contact us at{" "}
        <a href={`mailto:${LEGAL.contactEmail}`}>{LEGAL.contactEmail}</a>.
      </p>

      <h2>What we collect</h2>
      <ul>
        <li>
          <strong>Contact form:</strong> your first name, email address, phone
          number (if given), and your message.
        </li>
        <li>
          <strong>Sponsor bookings:</strong> business name, contact email and
          phone, your call-to-action link, the headline and body copy for your
          ad, and any image you upload.
        </li>
        <li>
          <strong>Event listings:</strong> your name, email, business/venue (if
          given), and the details of each event (name, venue, date, time, link).
        </li>
        <li>
          <strong>Payment information:</strong> payments are processed by Stripe.
          We do <strong>not</strong> receive or store your card details — only a
          payment reference and status.
        </li>
        <li>
          <strong>Technical data:</strong> basic server and security logs (such
          as IP address and request data) generated by our hosting provider.
        </li>
      </ul>

      <h2>Why we use it (lawful bases)</h2>
      <ul>
        <li>
          <strong>To respond to enquiries</strong> you send via the contact form
          — our legitimate interest in replying to you, or your consent.
        </li>
        <li>
          <strong>To fulfil bookings and listings</strong> you pay for —
          performance of a contract with you.
        </li>
        <li>
          <strong>To take payment and keep financial records</strong> — contract
          and our legal obligations (e.g. tax/accounting).
        </li>
        <li>
          <strong>To keep the service secure</strong> and prevent abuse — our
          legitimate interests.
        </li>
      </ul>

      <h2>Newsletter subscriptions</h2>
      <p>
        Our newsletter sign-up is handled by <strong>beehiiv</strong>. When you
        subscribe, your details are processed by beehiiv under their own privacy
        policy. You can unsubscribe at any time using the link in any email.
      </p>

      <h2>Who we share data with</h2>
      <p>
        We use trusted third-party processors to run the service. They only
        process your data on our instructions:
      </p>
      <ul>
        <li>
          <strong>Stripe</strong> — payment processing.
        </li>
        <li>
          <strong>Supabase</strong> — database and file storage for submissions.
        </li>
        <li>
          <strong>Vercel</strong> — website hosting.
        </li>
        <li>
          <strong>Resend</strong> — sending our team notification emails (where
          enabled).
        </li>
        <li>
          <strong>beehiiv</strong> — newsletter delivery.
        </li>
      </ul>
      <p>
        We do not sell your personal data. Some of these providers may process
        data outside the UK; where they do, appropriate safeguards (such as UK
        International Data Transfer Agreements or adequacy decisions) are in
        place.
      </p>

      <h2>How long we keep it</h2>
      <p>
        We keep booking and payment records for as long as required for legal and
        accounting purposes (typically six years). Contact messages and event
        submissions are kept for as long as needed to deal with your request and
        for our legitimate business records, then deleted.
      </p>

      <h2>Your rights</h2>
      <p>
        You have the right to access, correct, delete, restrict, or object to our
        use of your personal data, and the right to data portability. To exercise
        any of these, email{" "}
        <a href={`mailto:${LEGAL.contactEmail}`}>{LEGAL.contactEmail}</a>. You
        also have the right to complain to the Information Commissioner&rsquo;s
        Office (ICO) at{" "}
        <a href="https://ico.org.uk" target="_blank" rel="noopener noreferrer">
          ico.org.uk
        </a>
        .
      </p>

      <h2>Cookies</h2>
      <p>
        This website does not use advertising or analytics tracking cookies. Only
        essential cookies strictly necessary for the site to function may be set.
        If we add analytics in future, we will ask for your consent first.
      </p>

      <h2>Changes to this policy</h2>
      <p>
        We may update this policy from time to time. The &ldquo;last updated&rdquo;
        date above shows when it last changed.
      </p>
    </article>
  );
}
